### ISSUE TITLE
Implement versioneer to automate versioning & releases

### ISSUE THREAD

**Issue by raamana** [raamana/pyradigm#11]
Check https://github.com/warner/python-versioneer/blob/master/INSTALL.md

**Comment by viveksyngh** [comment]
@raamana  I will implement the versioneer and will create a PR once hacktoberfest starts.

**Comment by raamana** [comment]
Thanks Vivek, appreciate it. Hasn't the hacktober fest already started? :)

**Comment by viveksyngh** [comment]
It starts from October 1 right ?

**Comment by raamana** [comment]
my bad, I think the PRs have to be made on or after Oct 1st. No hurries, I can wait few days :)
