### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by stsievert** [raamana/pyradigm#2]
It would be useful to describe each function more completely, by documenting the inputs args and the return values. This will let people use your software more easily, and it would be the first thing I would look for.

A useful guideline to follow is probably the [numpy documentation standards][1]. Tools like [Sphinx] (with [numpydoc]) can autogenerate the documentation and put it online.

For example, the documentation for [MLDataset.add_sample][2] is currently

``` python
def add_sample(self, sample_id, features, label, class_id=None, feature_names=None):
    """Adds a new sample to the dataset with its features, label and class ID.
    This is the preferred way to construct the dataset."""
```

and following the NumPy doc standards would be something like

``` python
def add_sample(self, sample_id, features, label, class_id=None, feature_names=None):
    """Adds a new sample to the dataset with its features, label and class ID.

    This is the preferred way to construct the dataset.

    Parameters
    ----------
    sample_id : str, int
        The identifier that uniquely identifies this sample.
    features : list, ndarray
        The features for this example
    label : int, str
        The label for this example.
    class_id : int, str
        The class for this example
    feature_names : list
        The names for each feature. Assumed to be in the same order as `features`

    Raises
    ------
    ValueError
        If `sample_id` is already in the MLDataset

    """
```

(numpydoc used because that's what I'm familiar with)

[Sphinx]:http://www.sphinx-doc.org
[numpydoc]:https://github.com/numpy/numpydoc
[1]:https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
[2]:https://github.com/raamana/pyradigm/blob/9a168079b0ef6409d478bbeff8d47bde046a08d5/pyradigm/pyradigm.py#L184

**Comment by raamana** [comment]
Hey Scott, thanks for the detailed comment.  This is definitely at the top of my plan. I will wait for comments from all the reviewers, esp. regarding the API and inter-operability etc, to finalize the API, and document the more or less stable API thoroughly.

**Comment by stsievert** [comment]
Keep in mind that you can get free web hosting through GitHub by publishing the the gh-pages branch (which is then available at [username].github.io/[repo]

**Comment by raamana** [comment]
Thanks for the tip of gh-pages. I know of it [I think I did create one before] and readthedocs also, but they are not trivial to get done or to maintain. Once more and more people use this or contribute here, I can invest more time.

btw, 06d0113a454e13dfb869b9a948010da8537f444e should address the docs requirement.
